[project]
name = "odf_toolbox"
version = "0.6.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "icecream>=2.1.4",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]
