[project]
name = "odf-toolbox"
version = "0.5.1"
description = "A package for working with Ocean Data Format (ODF) files"
readme = "README.md"
authors = [
    { name = "Jeff Jackson", email = "jeffrey.jackson@dfo-mpo.gc.ca" }
]
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.workspace]
members = ["odf_toolbox"]
